server:
  port: 5003

spring:
  application:
    name: datacollectionservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.4:3307/getrand?serverTimezone=UTC
    username: mytest
    password: 1234

  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka
#  instance:
#    # 2초동안 하트비트가 수신되지 않으면 서비스 등록을 해제
#    lease-expiration-duration-in-seconds: 2

serp:
  api-key: 5f4cb96914761a3ef1df9f0ec2f4961edf20fb13b64d0ee68dc3ec9b0a18889f

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace

schedule:
  cron: 00 00 10 * * 1
  use: true